apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fintrack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/mfish18/fintrack-backend:4ce7f89
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: backend-config
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: fintrack-secrets
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fintrack-secrets
                key: DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: fintrack-secrets
                key: DB_NAME
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: fintrack-secrets
                key: JWT_SECRET
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10